---
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 20:10
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
---


```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = FALSE, fig.retina = 3)

library(flipbookr)
library(tidyverse)
```

```{r plot-results, include = FALSE}
mpg %>% 
  group_by(class) %>% 
  summarise(
    across(c(displ, cty, hwy), list)
    ) %>% 
  rowwise() %>% 
  mutate(
    across(
      where(is.list), 
      ~ goftest::ad.test(
        x = .x,
        null = "pnorm",
        mean = mean(.x),
        sd = sd(.x)
      )$p.value)
  )
```

`r chunk_reveal("plot-results", break_type = "auto")`

```{css, echo = FALSE}
@media print {
  .has-continuation {
    display: block;
  }
}
```
